### ISSUE TITLE
 Refine Demographics Filter Criteria in OpenEMR

### ISSUE THREAD

**Issue by KeerthikaSunchu** [iupui-soic/openemr#15]
### Describe the problem
The current "Demographics Filter Criteria" section in the CDR of OpenEMR encompasses parameters that don't strictly align with demographics.
![image](https://github.com/iupui-soic/openemr/assets/153401216/7ae68650-cef6-4624-b05b-412ce1809670)

### Describe the solution you'd like
**Reorganize Parameters:** Move non-demographic parameters (e.g., Medical issue, Diagnosis) to appropriate sections. 
(or)
**Rename Section:** Consider renaming "Demographics Filter Criteria" to accurately reflect its content.

**Comment by sunbiz** [comment]
Closing as fixed.
