### ISSUE TITLE
phpMyAdmin Docker Container Crashes Repeatedly 

### ISSUE THREAD

**Issue by madhurikokkalakonda** [iupui-soic/openemr#18]
Experiencing an ongoing issue where the phpMyAdmin Docker container consistently goes down.
![Screenshot 2024-04-17 153114](https://github.com/iupui-soic/openemr/assets/139369126/641b5c71-9e45-4a3e-bcce-5562e47b58e7)

Steps to Reproduce:
Log in with the user 'oemr'.
Check the status of all containers using the command: docker ps -a.
Identify if the phpMyAdmin container is running. If it is not running:
Restart the phpMyAdmin container using the command: docker restart [phpMyAdmin container ID].

Expected Behavior:
The phpMyAdmin container should be running without interruptions, ensuring continuous access for managing databases.

**Comment by sunbiz** [comment]
With the appropriate commands from our internal notes on phpmyadmin setup, with the correct Apache proxy setup, we are not encountering this issue of phpmyadmin exiting automatically on web20.

Closing issue as fixed!

**Comment by sunbiz** [comment]
add the [always restart policy](https://docs.docker.com/engine/containers/start-containers-automatically/#use-a-restart-policy) to be safe. 
```--restart always```
