### ISSUE TITLE
Missing units in Facility and Billing Facility dropdowns.

### ISSUE THREAD

**Issue by madhurikokkalakonda** [iupui-soic/openemr#20]
### Describe the bug
When creating a new encounter in the system, the 'Facility' and 'Billing Facility' dropdown menus in the encounter creation section of the system do not include all relevant units

### To Reproduce 
![Screenshot 2024-04-22 180453](https://github.com/iupui-soic/openemr/assets/139369126/5e4feffd-0476-4432-b53b-d46a4fb8e6c5)
![Screenshot 2024-04-22 180515](https://github.com/iupui-soic/openemr/assets/139369126/313af116-e145-400e-b2b3-21072a8c4a7e)

1. Go to the Encounters section in OpenEMR
2. Click on the plus icon beside the encounter section to add a new encounter.
3. Attempt to select a facility or billing facility.
4. Notice the absence of certain departments (Ex: Dental unit, Ophthalmology unit, Neurology unit, etc) in the dropdown menu.

### Expected behavior
Other units like the dental care unit, ophthalmology department, cardiology unit, gastroenterology department, and ENT department,  should be added to both the 'Facility' and 'Billing Facility' dropdown menus. This addition would allow users to select the appropriate department, ensuring all encounters can be recorded and billed accurately.

### Client configuration

- Browser:
- OpenEMR version:
- Operating system:

**Comment by KeerthikaSunchu** [comment]
-- Added more entries to the facility table of the openEMR databse in web 18 and it works.
INSERT INTO facility (NAME)
VALUES 
    ('Dental Care Unit'),
    ('Ophthalmology Department'),
    ('Cardiology Unit'),
    ('Gastroenterology Department'),
    ('ENT Department');

**Comment by KeerthikaSunchu** [comment]
![image](https://github.com/iupui-soic/openemr/assets/153401216/6f14eb50-7e5a-43ec-a08e-64e8dd8458be)
-- Added entries to the facility table.
INSERT INTO facility (name)
VALUES
('Allergy and Immunology Department'),
('Cardiology Unit'),
('Dental Care Unit'),
('Endocrinology Clinic'),
('ENT Department'),
('Gastroenterology Department'),
('Hematology/Oncology Department'),
('Infectious Disease Unit'),
('Nephrology Unit'),
('Ophthalmology Department'),
('Psychiatry Department'),
('Pulmonology Unit'),
('Rheumatology Clinic'),
('Your Clinic Name Here');

**Comment by KeerthikaSunchu** [comment]
New volumes has this '8qfT'. So it is fixed.
