### ISSUE TITLE
Adding Edit prompt to Medical Problems

### ISSUE THREAD

**Issue by madhurikokkalakonda** [iupui-soic/openemr#21]
### Describe the bug
The medical records title doesn't show that you can click to edit, which can lead to confusion as users may not realize where they can edit this information.

### To Reproduce
![Screenshot 2024-04-27 105310](https://github.com/iupui-soic/openemr/assets/139369126/1e7a158f-6aec-4737-8e70-bb997921ce6d)

1. Login to OpenEMR
2. Go to Patient Finder
3. Select the required patient
4. Access the medical problems section and ensure the title includes "(Click for editing)".

### Expected behavior
After following the above steps, the title for medical problems should include "(Click for editing)" to guide the users to modify the information.

### Client configuration

- Browser:
- OpenEMR version:
- Operating system:

**Comment by KeerthikaSunchu** [comment]
7.0.2 has the edit option.
