### ISSUE TITLE
Updating "Enc" to "Encounter" in Medical Problems

### ISSUE THREAD

**Issue by madhurikokkalakonda** [iupui-soic/openemr#22]
### Describe the bug

In the medical records display, the abbreviation "Enc" is used for Encounters, which might be confusing for users unfamiliar with the term. Using the full word "Encounter" would improve clarity.

### To Reproduce
![Screenshot 2024-04-27 105310](https://github.com/iupui-soic/openemr/assets/139369126/59934554-5172-42a5-9a1e-cb38d3dbfe60)

1. Login to OpenEMR
2. Go to Patient Finder and Select the patient
3. Go to the medical problems, find "Enc" and change it to "Encounter".

### Expected behavior
The "Enc" word should be expanded to "Encounter" to improve clarity and prevent confusion among users.

### Client configuration

- Browser:
- OpenEMR version:
- Operating system:

**Comment by yywini** [comment]
In version 7.0.2, the 'Enc' abbreviation no longer appears in the Medical Problems section,
![Screenshot 2024-10-26 212140](https://github.com/user-attachments/assets/4a0945d7-e675-415c-8044-f7be9acfab99)
