### ISSUE TITLE
Duplicate SSNs in patient_data Table Across 11k patients Instances 

### ISSUE THREAD

**Issue by KeerthikaSunchu** [iupui-soic/openemr#29]
### Describe the bug
There are duplicate Social Security Numbers (SSNs) in the patient_data table on both web12 and web13 instances.

### To Reproduce
![image](https://github.com/user-attachments/assets/a105118a-606e-42dc-b5bd-de6835fd544b)
![image](https://github.com/user-attachments/assets/cc455cd3-1fea-4146-b44c-1326d240d4dd)

1. Log into the web12 or web13 OpenEMR instance.
2. Navigate to the SQL Query section.
3. Execute the following SQL query to identify duplicate SSNs that are not null or empty:
SELECT ss, COUNT( * )
FROM patient_data
GROUP BY ss
HAVING COUNT( * ) > 1;
4. Review the query results which will list SSNs that appear more than once along with their count.

### Expected behavior
Each SSN in the patient_data table should be unique to maintain patient uniqueness across the system. 

### Client configuration
- OpenEMR version: 7.0.2

**Comment by sunbiz** [comment]
Thanks, @yywini for the fix commit here - https://github.com/sunbiz/oemr_synthea_notes/commit/1729f7b633e3adc4aa58c2f5a07b2d3689af1372

This should be included in the next update to the volumes.
