### ISSUE TITLE
Add Username Display to Header for Improved Accessibility in OpenEMR

### ISSUE THREAD

**Issue by KeerthikaSunchu** [iupui-soic/openemr#33]
### Describe the problem
In the OpenEMR interface, the header does not display the username. Currently, to view the username, users need to click on the profile icon, which is causing difficulties when grading students.
![image](https://github.com/user-attachments/assets/b8c801e3-b6e9-476c-bd0b-6ab72597a986)
This issue exists in both the 7.0.0 and 7.0.2 versions

### Describe the solution you'd like
To improve the user experience, the username should be displayed directly beside the profile button in the header. This would allow quick visibility of the username.

**Comment by sunbiz** [comment]
@KeerthikaSunchu, Thanks for the fix!!
