### ISSUE TITLE
Remove Clinicians from Access Control

### ISSUE THREAD

**Issue by madhurikokkalakonda** [iupui-soic/openemr#4]
### Describe the bug
The clinician's role in access control has limited or no use.
 
### To Reproduce
![Screenshot 2024-02-15 230305](https://github.com/iupui-soic/openemr/assets/139369126/ca26398e-097c-4b5b-a349-665227049a1c)
![Screenshot 2024-02-15 232415](https://github.com/iupui-soic/openemr/assets/139369126/c332dd6c-1d43-48ec-9ac7-68fcf9be7f1e)

1. Go to Admin
2. Click on Users and add users.
3. Scroll down to Access Control
4. Remove the clinician role

### Expected behavior

Clinician role removed from the access control list.

### Client configuration

- Browser:
- OpenEMR version:
- Operating system:

**Comment by sunbiz** [comment]
@madhurikokkalakonda are you working on this?? can you please make that change in the code here, as well as the database and then extract the volumes.

**Comment by madhurikokkalakonda** [comment]
@sunbiz, I'll make the changes and will update you with new extracted volumes.

**Comment by sunbiz** [comment]
@madhurikokkalakonda - please share the link to the extracted volume after testing.

**Comment by madhurikokkalakonda** [comment]
@sunbiz, Updated the extracted volumes link in the documentation.

**Comment by sunbiz** [comment]
Closing as fixed.
