### ISSUE TITLE
Alphabetic Input Allowed in CDR Reminder Intervals 

### ISSUE THREAD

**Issue by KeerthikaSunchu** [iupui-soic/openemr#5]
### Describe the bug
Input fields for CDR Reminder Intervals currently allow the entry of alphabetic characters, which leads to unexpected behavior.

###Steps to reproduce the behavior:

Add alphabetic characters ('abc') in any CDR field.
Click on Save.
Notice that the values in the fields are successfully saved.

### Expected behavior

The system should prevent the saving of entries with alphabetic characters and display a message indicating that only numerical values are allowed.

### Client configuration

- Browser:
- OpenEMR version: 7.0.2
- Operating system: Windows, Edge and Firefox browsers

**Comment by sunbiz** [comment]
Closing as fixed

**Comment by sunbiz** [comment]
thanks @tejaswiwmallidi for the reapplying the fix!
