### ISSUE TITLE
Vitals Section Enhancement - Quick Access to Vitals Form

### ISSUE THREAD

**Issue by KeerthikaSunchu** [iupui-soic/openemr#7]
### Describe the problem
In the current OpenEMR vitals section, there is no direct and quick way to access a comprehensive vitals form for inputting various patient vitals.

### Describe the solution you'd like
Add a new feature to the vitals section, represented by a pencil symbol, that allows users to quickly access a vitals form. When the user clicks on this symbol, a pop-up or a new page should appear, providing a user-friendly interface to input and update all relevant patient vitals. This would enhance the process of recording vitals and the overall usability of the OpenEMR system.

![image](https://github.com/iupui-soic/openemr/assets/153401216/8d38d679-a5e9-42f6-a9db-ffbe9e6bf4b2)

**Comment by sunbiz** [comment]
Closing as fixed
